spring.application.name=secureflow-backend


server.port=8080


spring.datasource.url=jdbc:mysql://localhost:3306/secureflow
spring.datasource.username=root
spring.datasource.password=root


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=MzJieXRlc2xvbmdzZWNyZXRrZXlmb3JzZWN1cmVmbG93YXBwbGljYXRpb24xMjM0NTY=
jwt.expiration=86400000